# This means your pipeline will run:
# - for merge requests
# - for branch pipelines UNLESS there is an open merge requests
# - for other branch pipelines
# - for tag pipelines
workflow:
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        -   if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
            when: never
        -   if: '$CI_COMMIT_BRANCH'
        -   if: '$CI_COMMIT_TAG'

# Variables for manual pipelines in gitlab frontend
# This is the API for Degree instance setup personnel
variables:
    TASK:
        value: ""
        description: "To set up a new Degree Platform instance, set this to 'setup instance'."
        options:
            # Empty value enables us to run a pipeline without needing to set up an instance
            - ""
            # Setting this to 'setup instance' will enable the instance setup job
            - "setup instance"
    TARGET:
        value: "production"
        description: "Choose whether to create the instance on the test (staging) or production server."
        options:
            - "test"
            - "production"
    INSTANCE_NAME:
        value: ""
        description: "The name of the instance to set up. It has to be lower case and a valid subdomain name! This will be checked by the setup script."
    INSTANCE_DOMAIN:
        value: ""
        description: "The domain to set up for the instance. When empty, the instance name will be used as instance subdomain and the domain will be degree40-test.tu-dortmund.de or degree40.tu-dortmund.de when target is 'test' or 'production' respectively. The domain has to exist and will be checked by the setup script! Example: \"zfsl.degree40.tu-dortmund.de\". HINT: If the Production/Staging Server URL changes, the setup script has to be adjusted as well!"

stages:
    - compile_resources
    - build
    - test
    - deploy

# When we want to execute a task, we want to skip the regular pipeline and only execute the task
include:
    # include task execution if required
    - local: ingress/.setup-instance.gitlab-ci.yml
      rules:
          - if: $TASK == "setup instance"

    # use default pipeline when no task was specified
    - local: ci/.deploy.gitlab-ci.yml
      rules:
          - if: $TASK == null || $TASK == ""
    - local: ci/.frontend.gitlab-ci.yml
      rules:
          - if: $TASK == null || $TASK == ""
    - local: ci/.package.gitlab-ci.yml
      rules:
          - if: $TASK == null || $TASK == ""
    - local: ci/.test.gitlab-ci.yml
      rules:
          - if: $TASK == null || $TASK == ""
