# This means your pipeline will run:
# - for merge requests
# - for branch pipelines UNLESS there is an open merge requests
# - for other branch pipelines
# - for tag pipelines
workflow:
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
        -   if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
            when: never
        -   if: '$CI_COMMIT_BRANCH'
        -   if: '$CI_COMMIT_TAG'

# Variables for scheduled pipelines in gitlab frontend
# This is the API for Degree instance setup personnel
variables:
    TASK:
        value: ""
        description: "The task to run. Can be 'setup instance' or 'update deployments'."
        options:
            # Empty value enables us to run a pipeline without needing to set up a new instance
            - ""
            - "setup instance"
    TARGET:
        value: "test"
        description: "The target environment to deploy to. Can be 'test' or 'production'."
        options:
            - "test"
            - "production"
    INSTANCE_NAME:
        value: ""
        description: "The name of the instance to set up. Only used when TASK is 'setup instance'."
    INSTANCE_DOMAIN:
        value: ""
        description: "The domain to set up for the instance. Only used when TASK is 'setup instance'."

stages:
    - compile_resources
    - build
    - test
    - deploy

# When we want to execute a task, we want to skip the regular pipeline and only execute the task
include:
    # include task execution if required
    - local: ingress/.setup-instance.gitlab-ci.yml
      rules:
          - if: '$TASK == "setup instance"'
    # use default pipeline when no task was specified
    - local: ci/.gitlab-ci.yml
      rules:
          - if: '$TASK == ""'
