version: '3.4'

services:
  api:
    build:
      context: ./
      dockerfile: deployment/docker/Dockerfile
#    healthcheck:
#      interval: 10s
#      timeout: 3s
#      retries: 3
#      start_period: 30s
    ports:
      - 8080:8080
      # if you add a hosts entry for "degree40.tu-dortmund.de 127.0.0.1", you can test the SAML authentication locally
      - 443:443
    depends_on:
      - db
    environment:
      LIVE_SYNC_JWT_PRIVATE_SIGNING_KEY: changeme-dev
      JWT_KEY: changeme-dev
    volumes:
      - ./api:/app:rw,cached
      # we had problems with non-updating build assets; so we mount this as non-cached.
      #- ./api/public/build/:/app/public/build:ro
      - app-var:/app/var

  redis:
    image: redis:6.0.1-alpine3.11
    ports:
      - 16379:6379

  redis-ui:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: 'redis:redis:6379:0'
      PORT: 8900
    ports:
      - 8002:8900

  #####
  # DB
  db:
    image: mariadb:10.2.25
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
      MYSQL_DATABASE: api
      MYSQL_USER: api-platform
      MYSQL_PASSWORD: '!ChangeMe!'
    volumes:
      - db-data:/var/lib/mysql:rw

#  # Logging & Metrics
#  vector:
#    build:
#      context: ./deployment/loggingSidecar
#    volumes:
#      - app-var:/app/var
#    environment:
#      VECTOR_CONFIG_FILE_NAME: vector.symfony+cadvisor.toml
#      LOGGING_CUSTOMER_TENANT: degree40
#      LOGGING_CUSTOMER_PROJECT: degree40.localdev
#      LOGGING_HOST_NAME: sebastians-mac
#      LOGGING_HOST_GROUP: sandstorm-devs
#
#  cadvisor:
#    # port 8080 /metrics
#    image: gcr.io/cadvisor/cadvisor:v0.37.5
#    privileged: true
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    devices:
#      - /dev/kmsg

volumes:
  app-var: {}
  db-data: {}
