##################################################
##### PRODUCTION ENVIRONMENT           ##########
##################################################

# Public ports:
#  - 80 -> API
#  - 13306 -> maria DB (used for Neos)
version: '3.4'

services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/deployment/data/traefik:/data
    command: |
      --providers.docker=true
      --entryPoints.web.address=:80
      # see https://docs.traefik.io/routing/entrypoints/#redirection - default redirect to HTTPS
      --entryPoints.web.http.redirections.entypoint.to=websecure
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --entryPoints.websecure.address=:443
      # default let's encrypt certificate resolvers
      --certificatesResolvers.letsencrypt.acme.email=technik@sandstorm-media.de
      --certificatesResolvers.letsencrypt.acme.storage=/data/acme.json
      --certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web
      
    container_name: traefik


  api:
    image: docker-hub.sandstorm.de/degree-4.0/code:master
    labels:
      - "traefik.http.routers.degree.rule=Host(`degree40.tu-dortmund.de`)"
      - "traefik.http.routers.degree.tls=true"
      - "traefik.http.routers.degree.tls.certresolver=letsencrypt"
      - traefik.http.services.degree.loadbalancer.server.port=8080
    #    healthcheck:
    #      interval: 10s
    #      timeout: 3s
    #      retries: 3
    #      start_period: 30s
    ports:
      - 8080
    depends_on:
      - db

  redis:
    image: redis:6.0.1-alpine3.11
    ports:
      - 6379

  redis-ui:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: 'redis:redis:6379:0'
      PORT: 8900
    ports:
      - 8002:8900

  #####
  # DB
  db:
    image: mariadb:10.2.25
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
      MYSQL_DATABASE: api
      MYSQL_USER: api-platform
      MYSQL_PASSWORD: '!ChangeMe!'
    volumes:
      - /home/deployment/data/mysql:/var/lib/mysql:rw

