version: '3.4'

services:
  api:
    build:
      context: ./
      dockerfile: deployment/docker/Dockerfile
#    healthcheck:
#      interval: 10s
#      timeout: 3s
#      retries: 3
#      start_period: 30s
    ports:
      - 8080:8080
      # if you add a hosts entry for "degree40.tu-dortmund.de 127.0.0.1", you can test the SAML authentication locally
      - 443:443
    depends_on:
      - db
    environment:
      LIVE_SYNC_JWT_PRIVATE_SIGNING_KEY: changeme-dev
      JWT_KEY: changeme-dev
    volumes:
      - ./api:/app:rw,cached
      # we had problems with non-updating build assets; so we mount this as non-cached.
      #- ./api/public/build/:/app/public/build:ro
      - app-var:/app/var

  redis:
    image: redis:6.0.1-alpine3.11
    ports:
      - 16379:6379

  redis-ui:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: 'redis:redis:6379:0'
      PORT: 8900
    ports:
      - 8002:8900

  #####
  # DB
  db:
    image: mariadb:10.2.25
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
      MYSQL_DATABASE: api
      MYSQL_USER: api-platform
      MYSQL_PASSWORD: '!ChangeMe!'
    volumes:
      - db-data:/var/lib/mysql:rw

volumes:
  app-var: {}
  db-data: {}
