easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\Account\User
            form:
                fields:
                    - email
                    - password

                            #        Exercise:
                            #            list:
                            #                fields: ['name', 'course.name']
                            #            class: App\Entity\Exercise\Exercise
                            #            form:
                            #                fields:
                            #                    - name
                            #                    - description
                            #                    -
                            #                        property: 'phases'
                            #                        type: 'collection'
                            #                        type_options:
                            #                            entry_type: 'App\Admin\Form\InlineExercisePhaseType'
                            #                            by_reference: false

    design:
        assets:
            #css:
            #   - 'build/app.css'
            js:
                - /build/runtime.js
                - /build/vendors~app.js
                - 'build/app.js'
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            # the following Twig template can be located anywhere in the application.
            # it can also be added to the twig.form_themes option to use it in the
            # entire application, not only the backend
            - 'form/json_schema_editor.html.twig'
