easy_admin:
    entities:
        # List the entity class name you want to manage
        Exercise:
            class: App\Entity\Exercise\Exercise
            form:
                fields:
                    - name
                    -
                        property: 'phases'
                        type: 'collection'
                        type_options:
                            entry_type: 'App\Form\InlineExercisePhaseType'
                            by_reference: false
