# all taken from https://github.com/onelogin/php-saml
hslavich_onelogin_saml:
    # Basic settings
    idp:
        entityId: 'https://sso.itmc.tu-dortmund.de/openam/tudo'
        singleSignOnService:
            url: 'https://sso.itmc.tu-dortmund.de/openam/SSOPOST/metaAlias/tudo/idp'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'https://sso.itmc.tu-dortmund.de/openam/IDPSloPOST/metaAlias/tudo/idp'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        # INFO: If the certificate of the IDP changes we as SP have to update it here as well.
        x509cert: |
            MIIE4zCCAsugAwIBAgIEchZQjzANBgkqhkiG9w0BAQwFADAiMSAwHgYDVQQDExdzc28uaXRtYy50
            dS1kb3J0bXVuZC5kZTAeFw0yMjA1MjcxMjA0MThaFw0zMjA1MjQxMjA0MThaMCIxIDAeBgNVBAMT
            F3Nzby5pdG1jLnR1LWRvcnRtdW5kLmRlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
            hOC2yO0mCdKy4HQbTwgZTwOCGGv6/LW1+eiTfrKDgVm7qukQbx/YB38jmmZboEPMF/aPmMNpOaeJ
            zHjNj43EY8GW5Pw6zml+qLKYXb78FH4L2fhTPRzNlbL0xjT4BIKmcwtoSJyP/9wOIkcrz0CNX+EK
            DazNiMxZd4JEyJmsOZX65qhtvH5Z6jucHfbzja5vpkeMqLX3GTZnIruYRP+glWpgmCuu+fJ8vI3t
            2uTE6D4IywNLGZe24f26FAVUfPlP0LlAG3uj7FwEDjHNCYFGy9j+QzbRnB0vMQlYO2K6OngIm3rP
            lPvP8gK0Jij334SEM4PI/T5sdGGrrdwJA41rn7C9rQY913plbkimKImPyThXnDFeiaAfbueyrOgu
            HlOKvM1hLnYNVunUwy0lTevxf6zRcvOThf6olGAXHVwcf0AC3uDI4SZ3ux7HKqZj42yMmEVdOsDF
            CNOVcA9GmyiLXhajwhUKonw0hSIknIk3Az0QTdZ//lXnnwTUjFcCzzno4qI0fylDBIuuCRP10QkV
            8y+ut83LfX1A7FQW34txpXuNbTbsPgRrzpMzJLB8GMYpi5nd2uO7FrafnVRbH0BIzD19+A78ilug
            cH9UlCBz8OlD4ovUCw3Ho9YHIEnMfzdo9K6v6nYQXdI/wFX7N8Ax3ggjKCJHQ0YqBoMGhPuNL4MC
            AwEAAaMhMB8wHQYDVR0OBBYEFFNPt6leA0S15MAsp/oFEXvZzOsXMA0GCSqGSIb3DQEBDAUAA4IC
            AQAZYQw/BBi8njCH81U6NI9wBCoriWSbp2VFmkI0zYPhDXmNplGAo2/otIc3JeAM+AtexMDlo5PQ
            HTtYbhADWshfxAbFbnIYeW6ZSpUXSus5GvglC5zkt6rMkgMdfwUBQLXnSrCm6RiftyVXXCXveCUQ
            f4LlYd/J0JXeZYXJ+bkHwUoh3PARband4vqHDROnp+Z6wKA2SYLJCFruVkTp5oXP1qx1+ToV6BAJ
            /zrfcDhbJ2FMDqPMP6/WigDWzAoa3HDfWi8AZL9AgWeBFr+zvLoWzGiEnaaBB5FiXnaNtXJ5Gnhf
            JoVryuMAo3G9vbVeqoWmXbRf9m7gk8l4VhFPoAdnqewVLEkUHPUh7FW0nARxWqOGDeFYBkWeG48T
            JN94t128tKg7uO69p7EKeYFjfyqZB54gVwXBqliTAtxMrYQjbDFv0nFJXtTgyFSHWf8aLq962hrY
            N8CTI6S9GjMVCp7uIkhCls1mRNnJFr+DFg2aCsdRU8ZDh+QOYWr8Mp+7qtrUhqy9zyIwbh0LWdSM
            h9lIh49xQhkT1o2w/5QI+ECixd+r6j8tMmVxHkZr+G1aW+TmY1UgWWTvKHOyNcM9ze9cEXFRZ7Nh
            8IrL3Jg8lEEQB3LcMHdVdbLjEic3KtKGcOWxj/Pr2a6FwXMdTkVFqcLSjDGc9/UP92RO1SNNPVsg
            rw==

    sp:
        entityId: 'https://degree40.tu-dortmund.de/saml/metadata'
        assertionConsumerService:
            url: 'https://degree40.tu-dortmund.de/saml/acs'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'https://degree40.tu-dortmund.de/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

        # discussed with Dennis Stracke / ITMC
        NameIDFormat: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'

    # optional settings begin here.

    # NOTE: we need to configure the base URL for SAML to work, as we are behind a reverse proxy.
    # !!! the URL must be EXACTLY like this, INCLUDING the trailing slash.
    baseurl: 'https://degree40.tu-dortmund.de/saml/'
    strict: true
    debug: false
    security:
        nameIdEncrypted:       false
        authnRequestsSigned:   false
        logoutRequestSigned:   false
        logoutResponseSigned:  false
        wantMessagesSigned:    false
        wantAssertionsSigned:  false
        wantNameIdEncrypted:   false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
    contactPerson:
        technical:
            givenName: 'Tech User'
            emailAddress: 'technik@sandstorm.de'
    organization:
        en:
            name: 'Example'
            displayname: 'Example'
            url: 'http://example.com'
