# all taken from https://github.com/onelogin/php-saml
hslavich_onelogin_saml:
    # Basic settings
    idp:
        entityId: 'https://sso.itmc.tu-dortmund.de:443/openam'
        singleSignOnService:
            url: 'https://sso.itmc.tu-dortmund.de:443/openam/SSOPOST/metaAlias/idp'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'https://sso.itmc.tu-dortmund.de:443/openam/IDPSloPOST/metaAlias/idp'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        x509cert: |
            MIIJ3jCCCMagAwIBAgIMJU1IawOszJfLe0n9MA0GCSqGSIb3DQEBCwUAMIGNMQsw
            CQYDVQQGEwJERTFFMEMGA1UECgw8VmVyZWluIHp1ciBGb2VyZGVydW5nIGVpbmVz
            IERldXRzY2hlbiBGb3JzY2h1bmdzbmV0emVzIGUuIFYuMRAwDgYDVQQLDAdERk4t
            UEtJMSUwIwYDVQQDDBxERk4tVmVyZWluIEdsb2JhbCBJc3N1aW5nIENBMB4XDTIx
            MDgzMTA2MjMyOFoXDTIyMTAwMTA2MjMyOFowgZoxCzAJBgNVBAYTAkRFMRwwGgYD
            VQQIDBNOb3JkcmhlaW4tV2VzdGZhbGVuMREwDwYDVQQHDAhEb3J0bXVuZDEpMCcG
            A1UECgwgVGVjaG5pc2NoZSBVbml2ZXJzaXRhZXQgRG9ydG11bmQxDTALBgNVBAsM
            BElUTUMxIDAeBgNVBAMMF3Nzby5pdG1jLnR1LWRvcnRtdW5kLmRlMIICIjANBgkq
            hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA42wJkKSc/ytLwFi/bHFS2rd6OJN6ZRFF
            yDOeSoGZjZHDFpitj1ZjoxDm+LpCvMFobNp6/Vepdrr8LQoBlOJ6PFgr0GHnb1gs
            0gDsYGDGBVQCNaUydcRNGbUp3Ri028OxD82SOqoftvwv6GjD2nPEaumvsjkKtKOY
            d3t/IJeVH3ql2hGbGAEkifJUIcFY3/+5sma+2HOYPTeepyjC+1bZV5Qmv5Qp1+82
            ixzwYhiCjDMEQLB5LJ21aqeDnbE9fVmIQnvNTmb4atPxAY1ozofeWDRPMZeVd2m7
            3JeFMGctBXQE8vQ63/hVA46ZpFeJlbYQM1b2GqKDvd14KbqX1wbqbYhtUVktJkjd
            h34LE1i52NmL19hCMk+A6ILrws5CARawWUOZmUarGGtJykuiItNQCheKSo74IISa
            yTEXawV8EuQw/PDIARtvgEkTP5nZpRKZfRVE9xEjrKLxmups5vLqlhBitIODVpjg
            UNKbCnw+ZpnAp7TXNwhvrBK7Xhdddbio0k5MWNJlIhOeBiq9MOhCKOA0r97cTFtb
            Z5V801MgEfVPFRW80LHydxDB047Z30Bolhv0CICnK7b7MQ01Rkrb7otZElU9uucK
            etxRfBM+RLnm4uI4rD7pLtz+bBJsbY85u6Ky6CCVuCvlB05XimeGF6Q11KdpCwCv
            T6Fm8fl3T2sCAwEAAaOCBS0wggUpMFcGA1UdIARQME4wCAYGZ4EMAQICMA0GCysG
            AQQBga0hgiweMA8GDSsGAQQBga0hgiwBAQQwEAYOKwYBBAGBrSGCLAEBBAkwEAYO
            KwYBBAGBrSGCLAIBBAkwCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0l
            BAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYEFElsK52hnTw4vWOnwwDn8OGj9GrLMB8G
            A1UdIwQYMBaAFGs6mIv58lOJ2uCtsjIeCR/oqjt0MIH0BgNVHREEgewwgemCF3Nz
            by5pdG1jLnR1LWRvcnRtdW5kLmRlghhzc28xLml0bWMudHUtZG9ydG11bmQuZGWC
            GHNzbzIuaXRtYy50dS1kb3J0bXVuZC5kZYIYc3NvMy5pdG1jLnR1LWRvcnRtdW5k
            LmRlghhzc280Lml0bWMudHUtZG9ydG11bmQuZGWCGHNzbzUuaXRtYy50dS1kb3J0
            bXVuZC5kZYIYc3NvNi5pdG1jLnR1LWRvcnRtdW5kLmRlghhzc283Lml0bWMudHUt
            ZG9ydG11bmQuZGWCGHNzbzguaXRtYy50dS1kb3J0bXVuZC5kZTCBjQYDVR0fBIGF
            MIGCMD+gPaA7hjlodHRwOi8vY2RwMS5wY2EuZGZuLmRlL2Rmbi1jYS1nbG9iYWwt
            ZzIvcHViL2NybC9jYWNybC5jcmwwP6A9oDuGOWh0dHA6Ly9jZHAyLnBjYS5kZm4u
            ZGUvZGZuLWNhLWdsb2JhbC1nMi9wdWIvY3JsL2NhY3JsLmNybDCB2wYIKwYBBQUH
            AQEEgc4wgcswMwYIKwYBBQUHMAGGJ2h0dHA6Ly9vY3NwLnBjYS5kZm4uZGUvT0NT
            UC1TZXJ2ZXIvT0NTUDBJBggrBgEFBQcwAoY9aHR0cDovL2NkcDEucGNhLmRmbi5k
            ZS9kZm4tY2EtZ2xvYmFsLWcyL3B1Yi9jYWNlcnQvY2FjZXJ0LmNydDBJBggrBgEF
            BQcwAoY9aHR0cDovL2NkcDIucGNhLmRmbi5kZS9kZm4tY2EtZ2xvYmFsLWcyL3B1
            Yi9jYWNlcnQvY2FjZXJ0LmNydDCCAfcGCisGAQQB1nkCBAIEggHnBIIB4wHhAHcA
            RqVV63X6kSAwtaKJafTzfREsQXS+/Um4havy/HD+bUcAAAF7muCJhAAABAMASDBG
            AiEAvYPyT1IdpL1k4RDk6wKTUcUe53A5i0QGNoUcw/aCZFECIQCiSQ9ktsWOwAu9
            EmqSnD10qs2kZFU1IWeXmRVYN4D+XwB3ACl5vvCeOTkh8FZzn2Old+W+V32cYAr4
            +U1dJlwlXceEAAABe5rgjXkAAAQDAEgwRgIhAJdsyVfE/24VTZUCYjCzIQc8z38a
            iNAUunRxudth13rMAiEAjjymFfRR6UDYjUYnY2sPeUfTmx19CuBv+zmPWaqsc9UA
            dgBvU3asMfAxGdiZAKRRFf93FRwR2QLBACkGjbIImjfZEwAAAXua4ImNAAAEAwBH
            MEUCIGaXOJh3eKsHvWPu+ouHpOO5hg7CMGKqYunFSWtKZvLaAiEAnj4rw/RpdLAL
            blf19Fs/wVcBkublDRUR1ZYrJctfZEIAdQBByMqx3yJGShDGoToJQodeTjGLGwPr
            60vHaPCQYpYG9gAAAXua4IqUAAAEAwBGMEQCIFsYPXf0+gGvWinbz3iSp2uGgs4y
            5jtBrM4ISbl6L9JZAiBB3GR8CYCgukDy5gILkI998a5yPLxt9x34zyhzsJ4E2jAN
            BgkqhkiG9w0BAQsFAAOCAQEAj0/VYOLOnBCFgnkUm+PsrDPHREMXk+2GFzEroYRA
            vX3BCvVwy4fVmBaZ5UsqSz9/8UKzOIBIarRm+1PZNepdnLUN+tr7tyY7p9P3QJE3
            CYj3xbnFB48G4BNctGlnyahTh2PXsnmRZNqviFPKEWYNiaJMacDLnsxsBkl6HvLw
            3o2afudbcnmMZHXfjbgW6FVsBLFHYHYDRL2B/HzFxmr2DbQ3m/N8hHCsGN8VaaTz
            nYpptgcNUPxgKf9kFn2KclmFsksMarujfd1FhQhrb0v0YdpzxBpsW5JPDwx48dL3
            Kax55lk02/gwIbesW8eAStmQdv3mOGLkZTqnOYElSvxUyA==

    sp:
        entityId: 'https://degree40.tu-dortmund.de/saml/metadata'
        assertionConsumerService:
            url: 'https://degree40.tu-dortmund.de/saml/acs'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: 'https://degree40.tu-dortmund.de/saml/logout'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'

        # discussed with Dennis Stracke / ITMC
        NameIDFormat: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'

    # optional settings begin here.

    # NOTE: we need to configure the base URL for SAML to work, as we are behind a reverse proxy.
    # !!! the URL must be EXACTLY like this, INCLUDING the trailing slash.
    baseurl: 'https://degree40.tu-dortmund.de/saml/'
    strict: true
    debug: false
    security:
        nameIdEncrypted:       false
        authnRequestsSigned:   false
        logoutRequestSigned:   false
        logoutResponseSigned:  false
        wantMessagesSigned:    false
        wantAssertionsSigned:  false
        wantNameIdEncrypted:   false
        requestedAuthnContext: true
        signMetadata: false
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
    contactPerson:
        technical:
            givenName: 'Tech User'
            emailAddress: 'technik@sandstorm.de'
    organization:
        en:
            name: 'Example'
            displayname: 'Example'
            url: 'http://example.com'
