# Read the documentation: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md
oneup_uploader:
    mappings:
        uploaded_videos:
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: oneup_flysystem.uploaded_videos_filesystem
        uploaded_material:
            frontend: dropzone
            storage:
                type: flysystem
                filesystem: oneup_flysystem.uploaded_material_filesystem

    orphanage:
        maxage: 86400
        directory: '%kernel.cache_dir%/uploader/orphanage'

    chunks:
        maxage: 86400
        storage:
            directory: '%kernel.cache_dir%/uploader/chunks'
