vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        exercise_material:
            uri_prefix: /exercise/material
            upload_destination: exercise_material_filesystem
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true