setup_new_instance:
    stage: deploy
    image: docker-hub.sandstorm.de/docker-infrastructure/php-app/build:8.3-v3
    tags:
        - jumphost
    before_script:
        #  install needed for DNS validation
        - apt update
        - apt install -y dnsutils
    script:
        # Target selection (test or production)
        - export SSH_KNOWN_HOSTS=$(if [ "$TARGET" == "test" ]; then echo $DEGREE_SERVER_URL_STAGING_KNOWN_HOSTS; else echo $DEGREE_SERVER_URL_PRODUCTION_KNOWN_HOSTS; fi)
        - export SSH_SERVER_URL=$(if [ "$TARGET" == "test" ]; then echo $DEGREE_SERVER_URL_STAGING; else echo $DEGREE_SERVER_URL_PRODUCTION; fi)
        - export SSH_USER=$(if [ "$TARGET" == "test" ]; then echo $DEGREE_SERVER_USER_STAGING; else echo $DEGREE_SERVER_USER_PRODUCTION; fi)
        # ssh
        - eval $(ssh-agent -s)
        - chmod 600 $SSH_PRIVATE_DEPLOY_KEY
        - ssh-add $SSH_PRIVATE_DEPLOY_KEY
        - mkdir -p ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        # deploy new instance
        - cd ingress
        # ensure that we can pull the degree latest image for the new instance
        - ssh $SSH_USER@$SSH_SERVER_URL "bash -c \"docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY\""
        - bash -c "./scripts/setup_instance.sh $TARGET $INSTANCE_NAME $INSTANCE_DOMAIN"
        # wait for the instance to be up
        - |
            WAIT_COUNT=0
            until [ $(curl -L -s -o /dev/null -w "%{http_code}" $INSTANCE_DOMAIN) == "200" ]
            do
                echo "Waiting for the instance at $INSTANCE_DOMAIN to be up..."
                sleep 1
                WAIT_COUNT=$((WAIT_COUNT+1))
                if [ $WAIT_COUNT -gt 60 ]; then
                    echo "Instance is not up after 1 minute. Exiting."
                    exit 1
                fi
            done
        # create admin user
        - echo "Setting up admin user from Gitlab CI variables."
        - ssh $SSH_USER@$SSH_SERVER_URL "cd deployments/$INSTANCE_NAME && docker compose exec degree bash -c \"./bin/console app:create-user --admin $DEGREE_INSTANCE_ADMIN_EMAIL $DEGREE_INSTANCE_ADMIN_PASSWORD\""
