package_app:
    stage: build
    rules:
        -   when: always
    interruptible: true
    image: docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # Install bash to run the versioning script
        - apk add --no-cache bash
        # Generate VERSION file (see deployment/docker/Dockerfile)
        - ./scripts/versioning.sh
        # build the degree image for this commit and push it to the registry
        - docker build -t $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG -f deployment/docker/Dockerfile .
        - docker push $CI_REGISTRY_IMAGE/app:$CI_COMMIT_REF_SLUG

build_e2e_testrunner:
    stage: build
    rules:
        -   when: always
    interruptible: true
    image: docker:dind
    script:
        - cd e2e-testrunner
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        # build the test runner image for this commit and push it to the registry
        - docker build -t $CI_REGISTRY_IMAGE/e2e-testrunner:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE/e2e-testrunner:$CI_COMMIT_REF_SLUG
        - cd ..
