# ansible-playbook -i inventories/production.yml -K server.yml
---
-   hosts: degree40.tu-dortmund.de
    remote_user: "{{ login_user }}"
    become: yes
    roles:
        - common
    tags:
        - common

-   hosts: degree40.tu-dortmund.de
    remote_user: "{{ login_user }}"
    become: yes
    roles:
        - docker
    tags:
        - docker
