controllers_schreibtisch:
    resource: ../../src/Schreibtisch/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_mediathek:
    resource: ../../src/Mediathek/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_data_export:
    resource: ../../src/DataExport/Controller
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_account:
    resource: ../../src/Account/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_standard:
    resource: ../../src/Standard/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_exercise:
    resource: ../../src/Exercise/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

controllers_easy-admin:
    resource: ../../src/Admin/Controller/
    type: annotation
    prefix:
        en: '/en'
        de: '/'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
