controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_mediathek:
    resource: ../../src/Mediathek/Controller/
    type: annotation


kernel:
    resource: ../../src/Kernel.php
    type: annotation
