controllers_mediathek:
    resource: ../../src/Mediathek/Controller/
    type: annotation

controllers_account:
    resource: ../../src/Account/Controller/
    type: annotation

controllers_exercise:
    resource: ../../src/Exercise/Controller/
    type: annotation


kernel:
    resource: ../../src/Kernel.php
    type: annotation
