doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: 'mariadb-10.11.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'App\Domain'
                alias: App
        filters:
            # TODO: let's just remove those?
            exercise_doctrine_filter:
                class: App\Security\DoctrineFilter\ExerciseDoctrineFilter
                enabled: true
                parameters:
                    userId: -1
            course_doctrine_filter:
                class: App\Security\DoctrineFilter\CourseDoctrineFilter
                enabled: true
                parameters:
                    userId: -1
