# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # !!!NOTE: we reconfigure this bundle in services.yaml to use the "vips" driver, but this is not officially supported. That's why
    # we cannot specify "vips" in the line below.
    # driver: "vips"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~
