# https://github.com/nbgrp/onelogin-saml-bundle?tab=readme-ov-file#configuration
nbgrp_onelogin_saml:
  onelogin_settings:
    # https://github.com/onelogin/php-saml
    default:
      # Mandatory SAML settings
      idp:
        entityId: '%env(SAML_IDP_ENTITY_ID)%'
        singleSignOnService:
          url: '%env(SAML_IDP_SSO_URL)%'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
          url: '%env(SAML_IDP_SLS_URL)%'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        x509cert: '%env(SAML_IDP_CERT)%'

      sp:
        entityId: '%env(SAML_SP_ENTITY_ID)%'  #  Default: '<request_scheme_and_host>/saml/metadata'
        assertionConsumerService:
          url: '%env(SAML_SP_ACS_URL)%'  #  Default: '<request_scheme_and_host>/saml/acs'
          binding:  'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
          url: '%env(SAML_SP_SLS_URL)%'  #  Default: '<request_scheme_and_host>/saml/logout'
          binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        NameIDFormat: 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'

      ##########################################
      # Optional SAML settings

      # NOTE: we need to configure the base URL for SAML to work, as we are behind a reverse proxy.
      # !!! the URL must be EXACTLY like this, INCLUDING the trailing slash.
      baseurl: '%env(SAML_BASE_URL)%'  #  Default: '<request_scheme_and_host>/saml/'
      strict: true
      debug: false # Default: true
      security:
        nameIdEncrypted: false
        authnRequestsSigned: false
        logoutRequestSigned: false
        logoutResponseSigned: false
        signMetadata: false
        wantMessagesSigned: false
        wantAssertionsEncrypted: false
        wantAssertionsSigned: false # Default: true
        wantNameId: false
        wantNameIdEncrypted: false
        requestedAuthnContext: true
        wantXMLValidation: true # Default: false
        relaxDestinationValidation: false
        destinationStrictlyMatches: true
        allowRepeatAttributeName: false
        rejectUnsolicitedResponsesWithInResponseTo: false
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
        encryption_algorithm: 'http://www.w3.org/2001/04/xmlenc#aes256-cbc'
        lowercaseUrlencoding: false
      contactPerson:
        technical:
          givenName: '%env(SAML_CONTACT_NAME)%'
          emailAddress: '%env(SAML_CONTACT_EMAIL)%'

      organization:
        en-US:
          name: 'Example'
          displayname: 'Example'
          url: 'http://example.com'
      compress:
        requests: true
        responses: true

  ##########################################
  # Optional parameters

  # for use with reverse proxies
  use_proxy_vars: true
  # idp_parameter_name: 'custom-idp'
  # entity_manager_name: 'custom-em'
